{
    "name": "Commercial Property Management",
    "summary": "Manage commercial property operations",
    "version": "16.0.1.2.0",
    "category": "Services/Property Management",
    "license": "LGPL-3",
    "depends": ["base", "contacts", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/commercial_property_sequence.xml",
        "data/commercial_property_unit_sequence.xml",
        "data/commercial_lease_sequence.xml",
        "data/commercial_property_application_sequence.xml",
        "data/commercial_property_maintenance_sequence.xml",
        "data/commercial_property_handover_sequence.xml",
        "data/commercial_property_integration_alert_actions.xml",
        "data/commercial_lease_cron.xml",
        "data/whatsapp_lead_policy.xml",
        "data/commercial_property_actions.xml",
        "data/commercial_property_unit_actions.xml",
        "data/commercial_property_lead_actions.xml",
        "data/commercial_property_visit_actions.xml",
        "data/commercial_property_reservation_actions.xml",
        "data/commercial_property_application_actions.xml",
        "data/commercial_tenant_actions.xml",
        "data/commercial_lease_actions.xml",
        "data/commercial_property_maintenance_actions.xml",
        "data/commercial_property_handover_actions.xml",
        "data/commercial_lease_penalty_actions.xml",
        "data/commercial_property_portfolio_actions.xml",
        "views/commercial_property_views.xml",
        "views/commercial_property_unit_views.xml",
        "views/commercial_property_lead_views.xml",
        "views/commercial_property_visit_views.xml",
        "views/commercial_property_reservation_views.xml",
        "views/commercial_property_application_views.xml",
        "views/commercial_property_integration_alert_views.xml",
        "views/commercial_tenant_views.xml",
        "views/commercial_lease_views.xml",
        "views/commercial_property_maintenance_views.xml",
        "views/commercial_property_handover_views.xml",
        "views/commercial_lease_financial_views.xml",
        "views/commercial_property_portfolio_views.xml",
        "views/res_config_settings_views.xml",
        "views/commercial_property_menus.xml",
        "data/commercial_property_unit_migration.xml",
    ],
    "application": True,
    "installable": True,
}
