{
    "name": "Job Hunter Management",
    "summary": "Track job opportunities and applications",
    "version": "16.0.9.0.0",
    "category": "Human Resources",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/job_hunter_sources.xml",
        "data/job_hunter_matching.xml",
        "data/job_hunter_sponsorship.xml",
        "data/job_hunter_documents.xml",
        "data/job_hunter_whatsapp.xml",
        "views/job_application_views.xml",
        "views/job_hunter_search_views.xml",
        "views/job_hunter_profile_views.xml",
        "views/job_hunter_sponsorship_views.xml",
        "views/job_hunter_document_views.xml",
        "views/job_hunter_whatsapp_views.xml",
        "views/job_application_submission_views.xml",
    ],
    "application": True,
    "installable": True,
}
