[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
list_db = True
proxy_mode = False
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_hard = 0
limit_memory_soft = 0
log_level = info
log_handler = :INFO
log_db = False
without_demo = all
